import re

with open('lib/i18n.ts', 'r', encoding='utf-8') as f:
    content = f.read()

new_keys = {
  'ro': """    feed_title: 'Toate anunțurile',
    feed_subtitle: 'Adopții, vânzări, ajutor medical și reproducere',
    type_all: '🐾 Toate',
    type_adoption: '❤️ Adopție',
    type_sale: '🛒 Vânzare',
    type_medical: '💊 Medical',
    type_breeding: '🌿 Reproducere',
    animal_cta_title_sale: 'Vrei să cumperi pe {name}? 🛒',
    animal_cta_desc_sale: 'Descarcă aplicația AnimalBond pentru a contacta vânzătorul și a afla toate detaliile despre {name}.',
    animal_cta_title_medical: 'Vrei să ajuți pe {name}? 💊',
    animal_cta_desc_medical: 'Descarcă aplicația AnimalBond pentru a contacta direct și a oferi sprijin medical pentru {name}.',
    animal_cta_title_breeding: 'Interesat de reproducere cu {name}? 🌿',
    animal_cta_desc_breeding: 'Descarcă aplicația AnimalBond pentru a contacta proprietarul și a discuta detalii despre {name}.',
    coming_soon: '🚀 În curând',
    coming_soon_desc: 'Aplicația AnimalBond va fi disponibilă în curând pe App Store și Google Play.',""",
  'en': """    feed_title: 'All listings',
    feed_subtitle: 'Adoptions, sales, medical help and breeding',
    type_all: '🐾 All',
    type_adoption: '❤️ Adoption',
    type_sale: '🛒 Sale',
    type_medical: '💊 Medical',
    type_breeding: '🌿 Breeding',
    animal_cta_title_sale: 'Want to buy {name}? 🛒',
    animal_cta_desc_sale: 'Download the AnimalBond app to contact the seller and get all the details about {name}.',
    animal_cta_title_medical: 'Want to help {name}? 💊',
    animal_cta_desc_medical: 'Download the AnimalBond app to contact directly and offer medical support for {name}.',
    animal_cta_title_breeding: 'Interested in breeding with {name}? 🌿',
    animal_cta_desc_breeding: 'Download the AnimalBond app to contact the owner and discuss details about {name}.',
    coming_soon: '🚀 Coming soon',
    coming_soon_desc: 'The AnimalBond app will be available soon on the App Store and Google Play.',""",
  'de': """    feed_title: 'Alle Anzeigen',
    feed_subtitle: 'Adoptionen, Verkäufe, medizinische Hilfe und Zucht',
    type_all: '🐾 Alle',
    type_adoption: '❤️ Adoption',
    type_sale: '🛒 Verkauf',
    type_medical: '💊 Medizin',
    type_breeding: '🌿 Zucht',
    animal_cta_title_sale: 'Möchtest du {name} kaufen? 🛒',
    animal_cta_desc_sale: 'Lade die AnimalBond-App herunter, um den Verkäufer zu kontaktieren und alle Details über {name} zu erfahren.',
    animal_cta_title_medical: 'Möchtest du {name} helfen? 💊',
    animal_cta_desc_medical: 'Lade die AnimalBond-App herunter, um direkt Kontakt aufzunehmen und medizinische Unterstützung für {name} anzubieten.',
    animal_cta_title_breeding: 'Interesse an Zucht mit {name}? 🌿',
    animal_cta_desc_breeding: 'Lade die AnimalBond-App herunter, um den Besitzer zu kontaktieren und Details über {name} zu besprechen.',
    coming_soon: '🚀 Bald verfügbar',
    coming_soon_desc: 'Die AnimalBond-App wird bald im App Store und Google Play verfügbar sein.',""",
  'fr': """    feed_title: 'Toutes les annonces',
    feed_subtitle: 'Adoptions, ventes, aide médicale et reproduction',
    type_all: '🐾 Tous',
    type_adoption: "❤️ Adoption",
    type_sale: '🛒 Vente',
    type_medical: '💊 Médical',
    type_breeding: '🌿 Reproduction',
    animal_cta_title_sale: 'Vous souhaitez acheter {name}? 🛒',
    animal_cta_desc_sale: "Téléchargez l'application AnimalBond pour contacter le vendeur et obtenir tous les détails sur {name}.",
    animal_cta_title_medical: 'Vous souhaitez aider {name}? 💊',
    animal_cta_desc_medical: "Téléchargez l'application AnimalBond pour contacter directement et offrir un soutien médical à {name}.",
    animal_cta_title_breeding: 'Intéressé par la reproduction avec {name}? 🌿',
    animal_cta_desc_breeding: "Téléchargez l'application AnimalBond pour contacter le propriétaire et discuter des détails sur {name}.",
    coming_soon: '🚀 Bientôt disponible',
    coming_soon_desc: "L'application AnimalBond sera bientôt disponible sur l'App Store et Google Play.",""",
  'it': """    feed_title: 'Tutti gli annunci',
    feed_subtitle: 'Adozioni, vendite, aiuto medico e riproduzione',
    type_all: '🐾 Tutti',
    type_adoption: "❤️ Adozione",
    type_sale: '🛒 Vendita',
    type_medical: '💊 Medico',
    type_breeding: '🌿 Riproduzione',
    animal_cta_title_sale: 'Vuoi comprare {name}? 🛒',
    animal_cta_desc_sale: "Scarica l'app AnimalBond per contattare il venditore e scoprire tutti i dettagli su {name}.",
    animal_cta_title_medical: 'Vuoi aiutare {name}? 💊',
    animal_cta_desc_medical: "Scarica l'app AnimalBond per contattare direttamente e offrire supporto medico a {name}.",
    animal_cta_title_breeding: 'Interessato alla riproduzione con {name}? 🌿',
    animal_cta_desc_breeding: "Scarica l'app AnimalBond per contattare il proprietario e discutere i dettagli su {name}.",
    coming_soon: '🚀 Prossimamente',
    coming_soon_desc: "L'app AnimalBond sarà presto disponibile sull'App Store e Google Play.",""",
  'es': """    feed_title: 'Todos los anuncios',
    feed_subtitle: 'Adopciones, ventas, ayuda médica y cría',
    type_all: '🐾 Todos',
    type_adoption: '❤️ Adopción',
    type_sale: '🛒 Venta',
    type_medical: '💊 Médico',
    type_breeding: '🌿 Cría',
    animal_cta_title_sale: '¿Quieres comprar a {name}? 🛒',
    animal_cta_desc_sale: 'Descarga la app AnimalBond para contactar al vendedor y obtener todos los detalles sobre {name}.',
    animal_cta_title_medical: '¿Quieres ayudar a {name}? 💊',
    animal_cta_desc_medical: 'Descarga la app AnimalBond para contactar directamente y ofrecer apoyo médico a {name}.',
    animal_cta_title_breeding: '¿Interesado en la cría con {name}? 🌿',
    animal_cta_desc_breeding: 'Descarga la app AnimalBond para contactar al propietario y discutir los detalles sobre {name}.',
    coming_soon: '🚀 Próximamente',
    coming_soon_desc: 'La app AnimalBond estará disponible pronto en el App Store y Google Play.',""",
  'hu': """    feed_title: 'Összes hirdetés',
    feed_subtitle: 'Örökbefogadás, eladás, orvosi segítség és szaporítás',
    type_all: '🐾 Összes',
    type_adoption: '❤️ Örökbefogadás',
    type_sale: '🛒 Eladás',
    type_medical: '💊 Orvosi',
    type_breeding: '🌿 Szaporítás',
    animal_cta_title_sale: 'Megvennéd {name}-t? 🛒',
    animal_cta_desc_sale: 'Töltsd le az AnimalBond alkalmazást, hogy kapcsolatba lépj az eladóval és megtudd az összes részletet {name}-ről.',
    animal_cta_title_medical: 'Szeretnél segíteni {name}-nek? 💊',
    animal_cta_desc_medical: 'Töltsd le az AnimalBond alkalmazást, hogy közvetlenül kapcsolatba lépj és orvosi támogatást nyújts {name}-nek.',
    animal_cta_title_breeding: 'Érdekel a szaporítás {name}-vel? 🌿',
    animal_cta_desc_breeding: 'Töltsd le az AnimalBond alkalmazást, hogy kapcsolatba lépj a tulajdonossal és megbeszéld a részleteket {name}-ről.',
    coming_soon: '🚀 Hamarosan',
    coming_soon_desc: 'Az AnimalBond alkalmazás hamarosan elérhető lesz az App Store-ban és a Google Play-en.',""",
}

lang_order = ['ro', 'en', 'de', 'fr', 'it', 'es', 'hu']
lang_idx = 0
lines = content.split('\n')
result = []

for line in lines:
    result.append(line)
    if 'animal_see_other:' in line and lang_idx < len(lang_order):
        lang = lang_order[lang_idx]
        result.append(new_keys[lang])
        lang_idx += 1

with open('lib/i18n.ts', 'w', encoding='utf-8') as f:
    f.write('\n'.join(result))

print(f'Done! Inserted keys for {lang_idx} languages.')
