import { COUNTRY_TO_LANG } from './i18n'

export type Country = { code: string; name: string; flag: string }

export const COUNTRIES: Country[] = [
  { code: 'RO', name: 'România',               flag: '🇷🇴' },
  { code: 'MD', name: 'Moldova',               flag: '🇲🇩' },
  { code: 'AT', name: 'Austria',               flag: '🇦🇹' },
  { code: 'BE', name: 'Belgia',                flag: '🇧🇪' },
  { code: 'BG', name: 'Bulgaria',              flag: '🇧🇬' },
  { code: 'HR', name: 'Croația',               flag: '🇭🇷' },
  { code: 'CY', name: 'Cipru',                 flag: '🇨🇾' },
  { code: 'CZ', name: 'Cehia',                 flag: '🇨🇿' },
  { code: 'DK', name: 'Danemarca',             flag: '🇩🇰' },
  { code: 'EE', name: 'Estonia',               flag: '🇪🇪' },
  { code: 'FI', name: 'Finlanda',              flag: '🇫🇮' },
  { code: 'FR', name: 'Franța',                flag: '🇫🇷' },
  { code: 'DE', name: 'Germania',              flag: '🇩🇪' },
  { code: 'GR', name: 'Grecia',                flag: '🇬🇷' },
  { code: 'HU', name: 'Ungaria',               flag: '🇭🇺' },
  { code: 'IE', name: 'Irlanda',               flag: '🇮🇪' },
  { code: 'IT', name: 'Italia',                flag: '🇮🇹' },
  { code: 'LV', name: 'Letonia',               flag: '🇱🇻' },
  { code: 'LT', name: 'Lituania',              flag: '🇱🇹' },
  { code: 'LU', name: 'Luxemburg',             flag: '🇱🇺' },
  { code: 'MT', name: 'Malta',                 flag: '🇲🇹' },
  { code: 'NL', name: 'Olanda',                flag: '🇳🇱' },
  { code: 'PL', name: 'Polonia',               flag: '🇵🇱' },
  { code: 'PT', name: 'Portugalia',            flag: '🇵🇹' },
  { code: 'SK', name: 'Slovacia',              flag: '🇸🇰' },
  { code: 'SI', name: 'Slovenia',              flag: '🇸🇮' },
  { code: 'ES', name: 'Spania',                flag: '🇪🇸' },
  { code: 'SE', name: 'Suedia',                flag: '🇸🇪' },
  { code: 'GB', name: 'Marea Britanie',        flag: '🇬🇧' },
  { code: 'CH', name: 'Elveția',               flag: '🇨🇭' },
  { code: 'NO', name: 'Norvegia',              flag: '🇳🇴' },
  { code: 'IS', name: 'Islanda',               flag: '🇮🇸' },
  { code: 'UA', name: 'Ucraina',               flag: '🇺🇦' },
  { code: 'RS', name: 'Serbia',                flag: '🇷🇸' },
  { code: 'AL', name: 'Albania',               flag: '🇦🇱' },
  { code: 'BA', name: 'Bosnia',                flag: '🇧🇦' },
  { code: 'ME', name: 'Muntenegru',            flag: '🇲🇪' },
  { code: 'MK', name: 'Macedonia de Nord',     flag: '🇲🇰' },
  { code: 'XK', name: 'Kosovo',                flag: '🇽🇰' },
  { code: 'TR', name: 'Turcia',                flag: '🇹🇷' },
  { code: 'GE', name: 'Georgia',               flag: '🇬🇪' },
  { code: 'AM', name: 'Armenia',               flag: '🇦🇲' },
  { code: 'AZ', name: 'Azerbaidjan',           flag: '🇦🇿' },
  { code: 'IL', name: 'Israel',                flag: '🇮🇱' },
  { code: 'AE', name: 'Emiratele Arabe',       flag: '🇦🇪' },
  { code: 'SA', name: 'Arabia Saudită',        flag: '🇸🇦' },
  { code: 'EG', name: 'Egipt',                 flag: '🇪🇬' },
  { code: 'MA', name: 'Maroc',                 flag: '🇲🇦' },
  { code: 'ZA', name: 'Africa de Sud',         flag: '🇿🇦' },
  { code: 'US', name: 'Statele Unite',         flag: '🇺🇸' },
  { code: 'CA', name: 'Canada',                flag: '🇨🇦' },
  { code: 'MX', name: 'Mexic',                 flag: '🇲🇽' },
  { code: 'BR', name: 'Brazilia',              flag: '🇧🇷' },
  { code: 'AR', name: 'Argentina',             flag: '🇦🇷' },
  { code: 'CL', name: 'Chile',                 flag: '🇨🇱' },
  { code: 'CO', name: 'Columbia',              flag: '🇨🇴' },
  { code: 'AU', name: 'Australia',             flag: '🇦🇺' },
  { code: 'NZ', name: 'Noua Zeelandă',         flag: '🇳🇿' },
  { code: 'JP', name: 'Japonia',               flag: '🇯🇵' },
  { code: 'KR', name: 'Coreea de Sud',         flag: '🇰🇷' },
  { code: 'SG', name: 'Singapore',             flag: '🇸🇬' },
  { code: 'IN', name: 'India',                 flag: '🇮🇳' },
  { code: 'TH', name: 'Thailanda',             flag: '🇹🇭' },
  { code: 'ID', name: 'Indonezia',             flag: '🇮🇩' },
  { code: 'PH', name: 'Filipine',              flag: '🇵🇭' },
  { code: 'VN', name: 'Vietnam',               flag: '🇻🇳' },
]

// Doar țările cu limbă SUPORTATĂ (10 limbi app) — exclude India, Grecia etc.
// Sursă UNICĂ pt toate ecranele (adopții, pierdute/găsite, medical, campanii) →
// dropdown-urile de țară să fie IDENTICE peste tot.
export const SUPPORTED_COUNTRIES: Country[] = COUNTRIES.filter(
  c => COUNTRY_TO_LANG[c.code] !== undefined
)
